# This is the configuration file for Ghostty.
#
# This template file has been automatically created at the following
# path since Ghostty couldn't find any existing config files on your system:
#
#   /home/shehab/.config/ghostty/config
#
# The template does not set any default options, since Ghostty ships
# with sensible defaults for all options. Users should only need to set
# options that they want to change from the default.
#
# Run `ghostty +show-config --default --docs` to view a list of
# all available config options and their default values.
#
# Additionally, each config option is also explained in detail
# on Ghostty's website, at https://ghostty.org/docs/config.

# Config syntax crash course
# ==========================
# # The config file consists of simple key-value pairs,
# # separated by equals signs.
# font-family = Iosevka
# window-padding-x = 2
#
# # Spacing around the equals sign does not matter.
# # All of these are identical:
# key=value
# key= value
# key =value
# key = value
#
# # Any line beginning with a # is a comment. It's not possible to put
# # a comment after a config option, since it would be interpreted as a
# # part of the value. For example, this will have a value of "#123abc":
# background = #123abc
#
# # Empty values are used to reset config keys to default.
# key =
#
# # Some config options have unique syntaxes for their value,
# # which is explained in the docs for that config option.
# # Just for example:
# resize-overlay-duration = 4s 200ms
# Background and foreground colors

# Background and foreground colors
background = #111827
foreground = #f2f4f8

# Standard colors (0–7)
palette = 0=#1B1D21
palette = 1=#FF5555
palette = 2=#1E90FF
palette = 3=#F1FA8C
palette = 4=#50FA7B
palette = 5=#FF79C6
palette = 6=#8BE9FD
palette = 7=#BBBBBB

# Bright colors (8–15)
palette = 8=#555555
palette = 9=#FF6E6E
palette = 10=#63B3FF
palette = 11=#FFFFA5
palette = 12=#69FF94
palette = 13=#FF92DF
palette = 14=#A4FFFF
palette = 15=#FFFFFF


selection-foreground = #376cdb
selection-background = #033259
selection-clear-on-typing = true


font-size = 18
font-family = MesloLGS Nerd Font Mono

shell-integration-features = no-cursor
cursor-color = #1E90FF

# cursor_shader = cursor-trail
# cursor_shader_decay = 0.1 0.4
# cursor_shader_threshold = 2
# cursor.animation = true


background-opacity = 0.92 
window-padding-y = 0
